### ISSUE TITLE
SQL Exception error when trying to access the Transaction menu, on the initializable function, when calling the SQL string variable.

### ISSUE THREAD

**Issue by MucaSan** [MucaSan/cash-flow#2]
/usr/lib/jvm/jdk-21-oracle-x64/bin/java -javaagent:/snap/intellij-idea-community/483/lib/idea_rt.jar=40451:/snap/intellij-idea-community/483/bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /home/svillar/.m2/repository/org/openjfx/javafx-controls/21/javafx-controls-21.jar:/home/svillar/.m2/repository/org/openjfx/javafx-graphics/21/javafx-graphics-21.jar:/home/svillar/.m2/repository/org/openjfx/javafx-base/21/javafx-base-21.jar:/home/svillar/.m2/repository/org/openjfx/javafx-fxml/21/javafx-fxml-21.jar:/home/svillar/.m2/repository/org/openjfx/javafx-media/21/javafx-media-21.jar:/home/svillar/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.8.10/kotlin-stdlib-common-1.8.10.jar:/home/svillar/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/usr/share/java/mysql-connector-j-8.3.0.jar:/home/svillar/.m2/repository/com/mysql/mysql-connector-j/8.3.0/mysql-connector-j-8.3.0.jar:/home/svillar/.m2/repository/com/google/protobuf/protobuf-java/3.25.1/protobuf-java-3.25.1.jar -p /home/svillar/.m2/repository/com/gluonhq/attach/storage/4.0.17/storage-4.0.17.jar:/home/svillar/IdeaProjects/cash-flow/cash-flow-control/target/classes:/home/svillar/.m2/repository/org/openjfx/javafx-graphics/21/javafx-graphics-21-linux.jar:/home/svillar/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.14.2/jackson-databind-2.14.2.jar:/home/svillar/.m2/repository/org/openjfx/javafx-base/21/javafx-base-21-linux.jar:/home/svillar/.m2/repository/com/gluonhq/attach/audio/4.0.17/audio-4.0.17.jar:/home/svillar/.m2/repository/org/openjfx/javafx-fxml/21/javafx-fxml-21-linux.jar:/home/svillar/.m2/repository/com/github/almasb/fxgl-core/17.3/fxgl-core-17.3.jar:/home/svillar/.m2/repository/com/github/almasb/fxgl-gameplay/17.3/fxgl-gameplay-17.3.jar:/home/svillar/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.14.2/jackson-core-2.14.2.jar:/home/svillar/.m2/repository/com/github/almasb/fxgl/17.3/fxgl-17.3.jar:/home/svillar/.m2/repository/com/gluonhq/attach/util/4.0.17/util-4.0.17.jar:/home/svillar/.m2/repository/org/openjfx/javafx-controls/21/javafx-controls-21-linux.jar:/home/svillar/.m2/repository/com/github/almasb/fxgl-entity/17.3/fxgl-entity-17.3.jar:/home/svillar/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.14.2/jackson-annotations-2.14.2.jar:/home/svillar/.m2/repository/com/github/almasb/fxgl-scene/17.3/fxgl-scene-17.3.jar:/home/svillar/.m2/repository/org/openjfx/javafx-media/21/javafx-media-21-linux.jar:/home/svillar/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.8.10/kotlin-stdlib-1.8.10.jar:/home/svillar/.m2/repository/com/gluonhq/attach/lifecycle/4.0.17/lifecycle-4.0.17.jar:/home/svillar/.m2/repository/com/github/almasb/fxgl-io/17.3/fxgl-io-17.3.jar -m com.example.cashflowcontrol/application.cashflowcontrol.MainApplication
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.idSession = SessionDB.id INNER JOIN PaymentDB on TransactionDB.idPayment = Paym' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1208)
	at com.example.cashflowcontrol/controllers.cashflowcontrol.ManageMenuController.initialize(ManageMenuController.java:85)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2670)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2563)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3376)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3332)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3300)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3272)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3248)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.load(FXMLLoader.java:3241)
	at com.example.cashflowcontrol/generalPurposesClasses.cashflowcontrol.ChangeWindow.setNewWindowFromMouseClick(ChangeWindow.java:21)
	at com.example.cashflowcontrol/controllers.cashflowcontrol.MenuController.buttonManageClick(MenuController.java:46)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at javafx.base@21/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:270)
	at javafx.fxml@21/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml@21/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1853)
	at javafx.fxml@21/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1726)
	at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21/javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3688)
	at javafx.graphics@21/javafx.scene.Scene$MouseHandler.process(Scene.java:3993)
	at javafx.graphics@21/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@21/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
	at java.base/java.lang.Thread.run(Thread.java:1583)
javafx.fxml.LoadException: 
/home/svillar/IdeaProjects/cash-flow/cash-flow-control/target/classes/fxml.controllers.manage/manageMenu.fxml

	at javafx.fxml@21/javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2722)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2700)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2563)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3376)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3332)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3300)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3272)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3248)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.load(FXMLLoader.java:3241)
	at com.example.cashflowcontrol/generalPurposesClasses.cashflowcontrol.ChangeWindow.setNewWindowFromMouseClick(ChangeWindow.java:21)
	at com.example.cashflowcontrol/controllers.cashflowcontrol.MenuController.buttonManageClick(MenuController.java:46)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at javafx.base@21/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:270)
	at javafx.fxml@21/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml@21/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1853)
	at javafx.fxml@21/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1726)
	at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21/javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3688)
	at javafx.graphics@21/javafx.scene.Scene$MouseHandler.process(Scene.java:3993)
	at javafx.graphics@21/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@21/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.control.TableView.setItems(javafx.collections.ObservableList)" because "this.tableManage" is null
	at com.example.cashflowcontrol/controllers.cashflowcontrol.ManageMenuController.initialize(ManageMenuController.java:158)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2670)
	... 46 more

**Comment by MucaSan** [comment]
issue solved, on was concated without a given space
