### ISSUE TITLE
Issue when trying to load the Transaction Manage session, on the FXML PATH

### ISSUE THREAD

**Issue by MucaSan** [MucaSan/cash-flow#3]
javafx.fxml.LoadException: 
/home/svillar/IdeaProjects/cash-flow/cash-flow-control/target/classes/fxml.controllers.manage/manageMenu.fxml

	at javafx.fxml@21/javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2722)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2700)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2563)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3376)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3332)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3300)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3272)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3248)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.load(FXMLLoader.java:3241)
	at com.example.cashflowcontrol/generalPurposesClasses.cashflowcontrol.ChangeWindow.setNewWindowFromMouseClick(ChangeWindow.java:21)
	at com.example.cashflowcontrol/controllers.cashflowcontrol.MenuController.buttonManageClick(MenuController.java:46)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at javafx.base@21/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:270)
	at javafx.fxml@21/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml@21/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1853)
	at javafx.fxml@21/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1726)
	at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21/javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3688)
	at javafx.graphics@21/javafx.scene.Scene$MouseHandler.process(Scene.java:3993)
	at javafx.graphics@21/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@21/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.control.TableView.setItems(javafx.collections.ObservableList)" because "this.tableManage" is null
	at com.example.cashflowcontrol/controllers.cashflowcontrol.ManageMenuController.initialize(ManageMenuController.java:160)
	at javafx.fxml@21/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2670)
	... 46 more

**Comment by MucaSan** [comment]
Problem solved by setting the tableManage fx:id into the FXML file, which was missing.
